//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvanRetoCurso.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesIvan
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> Birhtday { get; set; }
        public string RCF { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public int PositionId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual PositionsIvan PositionsIvan { get; set; }
    }
}
